app_id: "1f8e9180-9bb2-4980-9c10-b9602fd6f304"
app_secret: "puAC79;^)pysyfXIQDW005_"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read user.readbasic.all"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
