# Generated by Django 3.2.4 on 2022-11-02 16:48

import chat.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Array',
            fields=[
                ('user', models.Field(default=[], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='dm', max_length=6)),
                ('members', djongo.models.fields.ArrayField(default=[], model_container=chat.models.Array)),
                ('blocked', djongo.models.fields.ArrayField(default=[], model_container=chat.models.Array)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sender', models.TextField(default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(default=None)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapi.chatroom')),
            ],
        ),
    ]
