# Generated by Django 4.2 on 2023-05-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_dm',
        ),
    ]
