# Generated by Django 4.2.1 on 2023-05-12 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapi', '0002_remove_chat_unique_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'chat_members': models.F('chat_members')}, related_name='group_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chat_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
