# Generated by Django 4.2.1 on 2023-05-12 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapi', '0003_alter_chat_admins_alter_chat_is_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'chat_members': models.F('chat_members')}, null=True, related_name='group_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(null=True, related_name='chat_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
