# Generated by Django 3.2.4 on 2021-07-06 16:50

import chat.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210706_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='blocked',
            field=djongo.models.fields.ArrayField(default=[], model_container=chat.models.Array),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=djongo.models.fields.ArrayField(default=[], model_container=chat.models.Array),
        ),
    ]
