# Generated by Django 3.2.4 on 2021-07-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('chat', '0003_auto_20210706_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
