# Generated by Django 3.2.4 on 2021-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Array',
            fields=[
                ('user', models.Field(default=[], primary_key=True, serialize=False)),
            ],
        ),
    ]
