# Generated by Django 3.2.4 on 2021-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
