# Generated by Django 3.2.4 on 2021-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='offline', max_length=10),
        ),
    ]
