# Generated by Django 3.2.4 on 2021-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0004_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
