# Generated by Django 3.2.4 on 2021-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0005_auto_20210706_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneno',
            field=models.CharField(default='', max_length=13),
        ),
    ]
