# Generated by Django 3.2.4 on 2021-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0006_alter_users_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cover',
            field=models.CharField(default='', max_length=30),
        ),
    ]
