# Generated by Django 3.2.4 on 2022-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=65)),
                ('phone_no', models.CharField(default='', max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.CharField(default='offline', max_length=10)),
                ('profile', models.CharField(default='', max_length=30)),
                ('cover', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
