# Generated by Django 3.2.4 on 2021-07-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_title'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chat_members',
        ),
        migrations.AddField(
            model_name='group',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
