# Generated by Django 3.2.4 on 2021-07-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chat',
        ),
    ]
