# Generated by Django 3.2.4 on 2021-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='av',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='group',
            name='cover',
            field=models.CharField(default='', max_length=60),
        ),
    ]
